name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: swift -version
      - name: Build
        run: swift build
