name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: swift -version
      - name: Install Dependencies
        run: |
          sed -i 's/bionic/focal/g' /etc/apt/sources.list
          apt-get update
          apt-get install -y libplayerctl-dev
      - name: Build
        run: swift build
